---
- name: Backup production data from GSATI
  hosts: gsati-production
  gather_facts: yes
  sudo: yes
  tasks:
  - name: Include secure variables
    include_vars: secure.yml.aes

  - name: Copy prod_backup inspect
    copy:
      src: prod_backup_inspect.sh
      dest: /tmp/prod_backup_inspect.sh
      mode: 0700
      owner: root
      group: root

  - name: Get production backup var
    command: /tmp/prod_backup_inspect.sh
    register: backup_dir

  - name: Remove backup volume directory
    file:
      path: "{{ backup_dir.stdout }}"
      state: absent

  - name: Create backup volume directory
    file:
      path: "{{ backup_dir.stdout }}"
      state: directory

  - name: Create backup of production
    shell: docker start -a prod_backup
    register: backup_state

  - name: Copy backup to temporary graph.db folder
    shell: cp -R {{ backup_dir.stdout }} /tmp/graph.db

  - name: Set owner as deploy
    file:
      path: /tmp/graph.db
      owner: deploy
      mode: 0755
      state: directory
      recurse: yes

  - name: Make current date var
    shell: echo `date +%s`
    register: current_date

  - name: "Archive the backed up data "
    shell: tar -cf - /tmp/graph.db/ | bzip2 -c9 > /tmp/proddata-{{ current_date.stdout }}.tar.bz2
    sudo: no

  - name: Upload backup to S3
    s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: ds-core-backup
      object: proddata-{{ current_date.stdout }}.tar.bz2
      src: /tmp/proddata-{{ current_date.stdout }}.tar.bz2
      mode: put

  - name: Remove backup file
    file:
      path: /tmp/proddata-{{ current_date.stdout }}.tar.bz2
      state: absent

  - name: Remove temporary graph.db directory
    file:
      path: /tmp/graph.db
      state: absent

  - name:
    slack:
      token: "{{ slack_token }}"
      domain: zavalasystems.slack.com
      msg: "Production databse back up succeeded."
      channel: "#build"

