---
- hosts: all
  sudo: yes
  tasks:
  - name: Install docker-py
    pip:
      name: docker-py

  - name: Pull API image
    command: docker pull likwid/stuff:{{ version }}
    sudo: False

  - name: Pull Web image
    command: docker pull likwid/frontend:{{ version }}
    sudo: False

  - name: Stopping remote container
    shell: docker stop api web
    ignore_errors: True

  - name: "Start API {{ version }}"
    docker:
      name: api
      image: likwid/stuff:{{ version }}
      ports: "8000:8080"
      links: "db:db"
      detach: yes

  - name: "Start Web {{ version }}"
    docker:
      name: web
      image: likwid/frontend:{{ version }}
      ports: "80:8001"
      links: "api:api"
      detach: yes

  - name: Notify hipchat of success
    hipchat:
      token: "{{ hipchat_token }}"
      room: Build
      msg: Deploy {{ version }} succeeded

    # - name: Notify hipchat of failure
    # hipchat:
    #   token: "{{ hipchat_token }}"
    #   room: Build
    #   msg: Deploy {{ version }} failed
    #   when:
