---
- hosts: all
  sudo: yes
  tasks:
  - name: Install docker-py
    pip:
      name: docker-py

  - name: Pull containers
    docker:
      image: "{{ item }}:{{ version }}"
      state: present
    with_items:
    - likwid/stuff
    - likwid/frontend

  - name: Stop containers
    docker:
      name: "{{ item.name }}"
      image: "{{ item.image }}"
      state: stopped
    with_items:
    - image: likwid/stuff
      name: api
    - image: likwid/frontend
      name: web

  - name: "Start API {{ version }}"
    docker:
      name: api
      image: likwid/stuff:{{ version }}
      ports: "8080"
      links: "db:db"
      detach: yes
      state: running

  - name: "Start Web {{ version }}"
    docker:
      name: web
      image: likwid/frontend:{{ version }}
      ports: ["80:80", "8000:8000"]
      links: "api:api"
      detach: yes
      state: running

  - name: Notify hipchat of success
    hipchat:
      token: "{{ hipchat_token }}"
      room: Build
      msg: Deploy {{ version }} succeeded

    # - name: Notify hipchat of failure
    # hipchat:
    #   token: "{{ hipchat_token }}"
    #   room: Build
    #   msg: Deploy {{ version }} failed
    #   when: