---
- hosts: all
  sudo: no
  tasks:
  # - name: Install docker-py
  #   pip:
  #     name: docker-py

  - name: Pull containers
    command: "docker pull ds-sysadmin:5000/{{ item }}:{{ version }}"
    sudo: no
    with_items:
    - core-api
    - core-ui

  - name: Stop containers
    docker:
      name: "{{ item.name }}"
      image: "{{ item.image }}"
      state: absent
    with_items:
    - image: ds-sysadmin:5000/core-api
      name: api
    - image: ds-sysadmin:5000/core-ui
      name: web

  - name: "Start API {{ version }}"
    docker:
      name: api
      image: ds-sysadmin:5000/core-api:{{ version }}
      ports: "8080"
      links: "db:db"
      detach: yes
      state: running

  - name: "Start Web {{ version }}"
    docker:
      name: web
      image: ds-sysadmin:5000/core-ui:{{ version }}
      ports: ["80:80", "8000:8000"]
      links: "api:api"
      detach: yes
      state: running

  - name: Notify hipchat of success
    hipchat:
      token: "{{ hipchat_token }}"
      room: Build
      msg: Deploy {{ version }} succeeded

    # - name: Notify hipchat of failure
    # hipchat:
    #   token: "{{ hipchat_token }}"
    #   room: Build
    #   msg: Deploy {{ version }} failed
    #   when: