---
- hosts: all
  sudo: no
  tasks:

  - name: Pull containers
    command: "docker pull ds-sysadmin:5000/{{ item }}:{{ version }}"
    with_items:
    - core-api
    - core-ui

  - name: Stop container services
    service:
      name: "{{ item }}"
      state: stopped
    with_items:
    - core-api
    - core-ui

  - name: Stop containers
    docker:
      name: "{{ item.name }}"
      image: "{{ item.image }}"
      state: absent
    with_items:
    - image: ds-sysadmin:5000/core-api
      name: core-api
    - image: ds-sysadmin:5000/core-ui
      name: core-ui

  - name: "Start API {{ version }}"
    docker:
      name: core-api
      image: ds-sysadmin:5000/core-api:{{ version }}
      ports: "8080"
      links: "db:db"

  - name: "Start Web {{ version }}"
    docker:
      name: core-ui
      image: ds-sysadmin:5000/core-ui:{{ version }}
      ports: ["80:80", "8000:8000"]
      links: "core-api:api"

  - name: Start container services
    service:
      name: "{{ item }}"
      state: started
    with_items:
    - core-api
    - core-ui

  - name: Notify hipchat of success
    hipchat:
      token: "{{ hipchat_token }}"
      room: Build
      msg: Deploy {{ version }} succeeded

    # - name: Notify hipchat of failure
    # hipchat:
    #   token: "{{ hipchat_token }}"
    #   room: Build
    #   msg: Deploy {{ version }} failed
    #   when: