---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Get sha1 variable
    command: git rev-parse --short HEAD
    register: core_version

  - name: Notify Build Start
    uri:
      method: POST
      url: https://api.hipchat.com/v2/room/{{ ansible_env.HIPCHAT_ROOM }}/notification?auth_token={{ ansible_env.$HIPCHAT_KEY }}
      HEADER_Content-Type: application/json
      body: >
        \x7B "message": "Building revision {{ core_version.stdout }}" \x7D

  - name: npm install
    npm:
      path: /home/ubuntu/build

  - name: Build docker image
    docker_image: 
      name: likwid/stuff
      state: present
      path: /home/ubuntu/build
      tag: "{{ core_version.stdout }}"

  - name: Test image
    docker:
      image: likwid/stuff:{{ core_version.stdout }}
      command: grunt

  - name: Inspect test results
    shell: "docker inspect --format='\x7B\x7B.State.ExitCode\x7D\x7D' `docker ps -lq`"
    register: test_return_code
    failed_when: "test_return_code.stdout != 0" 

- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Notify Build Success
    uri:
      method: POST
      url: https://api.hipchat.com/v2/room/{{ ansible_env.HIPCHAT_ROOM }}/notification?auth_token={{ ansible_env.$HIPCHAT_KEY }}
      HEADER_Content-Type: application/json
      body: '{ "message": "Build {{ core_version.stdout }} succeeded." }'
    when: test_return_code.stdout == 0

  - name: Notify Build Failure
    uri:
      method: POST
      url: https://api.hipchat.com/v2/room/{{ ansible_env.HIPCHAT_ROOM }}/notification?auth_token={{ ansible_env.$HIPCHAT_KEY }}
      HEADER_Content-Type: application/json
      body: '{ "message": "Build {{ core_version.stdout }} failed." }' 
    when: test_return_code.stdout != 0

  - name: Failure Reason
    debug:
      msg: "Return code was {{ test_return_code.stdout }}"
    when: test_return_code.stdout != 0